# docker-compose.yml
services:
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: unless-stopped
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  chainlit:
    build: .
    container_name: rag-rncp
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./faiss_index:/app/faiss_index

volumes:
  ollama_data: